### ISSUE TITLE
Description-fält i ApiData för varje feature

### ISSUE THREAD

**Issue by Toubic** [1DV611/effect-reklambyra#104]
Hade vart bra om ni lägger till ett description-fält för varje feature så jag enkelt kan iterera över features:

http://i.imgur.com/Ke2IS7l.jpg

**Comment by larswww** [comment]
lägger du rimligtvis i view istället för att, återigen, lagra det i varje db objekt och skapa redundancy. Då blir det också enklare att lägga till fler beskrivningar för framtida fält...

**Comment by larswww** [comment]
Ha alltså dessa strängar i din JS som ligger på klienten. Beskrivningar är presentation, presentation har du i view, i detta fall är view klienten i html och css. Du behöver inte ha det i databasen.
