### ISSUE TITLE
Frågor för kundmöte

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#12]
Lars:
- Vad har dom för miljö annars?
- Andra webappar som är clientfacing?
- Design / stilmall?
- Corp branding? 
- Behövs datan delas in i perioder? 
- Hur låter det med att varje kund aktiverar varje social medie kanal enskilt?
- Behöver varje PDF ha enskilts företags logo/färgtema?
- Kommer appen ligga på egen domän eller ska den integreras i deras site eller dylikt?
- Kan ni skicka oss mer PDF exempel så vi kan se hur data/diagram typer ev varierar?
- Hur känslig är kundens data?
- Kod kommentarer på SV / EN?
- Ska alla stats sammanställas eller för varje enskild kund? 
- Kan vi få en statistik / data dump? I.e. statistik från varje sociala kanal och ert sammanställningsark.

**Comment by Toubic** [comment]
Tobias:

* Hur vill ni att sammanfattningstexten ska vara utformad?
* Vilka diagram ska ingå?
* Projektnamn? Projekt Effekt?
* Kodkommentarer på svenska/engelska?

**Comment by sehnpaa** [comment]
Peter:
- Vad tror de om möjligheterna att hämta historisk data från API:erna (så vi kan slippa lagra)?
- Finns det något "Minimum browser requirement"?
- Har ni några önskemål om testverktyg, eller hur testing ska ske?
