### ISSUE TITLE
Auktorisering

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#13]
Vilken auth provider ska vi använda?
- Auth0 (http://www.auth0.com/) (fungerar med passport)

**Comment by Toubic** [comment]
Stormpath? (https://docs.stormpath.com/rest/product-guide/latest/auth_z.html)

**Comment by larswww** [comment]
Passport gör väl bara Autentication men inte Authorization? Iom att vi behöver tillstånd på t ex twitter och facebook at hämta ut data.
- med ett konto på auth0 kan dom även skapa kund login manuellt med användarnamn och lösenord, vilket önskas i prelim requirements.
