### ISSUE TITLE
Lagring/databas?

### ISSUE THREAD

**Issue by Toubic** [1DV611/effect-reklambyra#17]
Vilken typ av lagring ska vi ha och vad ska vi lagra?

**Comment by Toubic** [comment]
Firebase Realtime Database? (https://firebase.google.com/docs/database/)
mLab? (https://mlab.com/)

**Comment by larswww** [comment]
Behöver PDFerna lagras? Skapas dom inte on the fly från datan som är lagad? Så laddar kunden hem och sparar sina PDFer?

**Comment by Toubic** [comment]
Japp det e sant

**Comment by larswww** [comment]
DigitalOcean MEAN stack eftersom jag och Rasmus är bekant med det redan. Besultat på möte 10 apr
