### ISSUE TITLE
Klienten

### ISSUE THREAD

**Issue by Toubic** [1DV611/effect-reklambyra#20]
Tänkte att vi kunde specificera vilka språk/tekniker vi ska ha på klienten.

**Comment by Toubic** [comment]
* JavaScript
* Node.js
* HTML-CSS
* Bootstrap
* express-handlebars? (https://www.npmjs.com/package/express-handlebars)
* Socket.IO? (https://socket.io/)

**Comment by meristakovska** [comment]
~~[ChartsJS](http://www.chartjs.org/) eller [Google Charts](https://developers.google.com/chart/?)?~~ #14

**Comment by larswww** [comment]
express-handlebars, bootstrap, js es5 sammanfattningsvis alltså
