### ISSUE TITLE
Git push to demo server

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#32]

**Comment by rassek96** [comment]
I repot ni vill pusha:
git remote add <name> ssh://root@188.226.145.92/var/repo/site.git
git push <name>

Det finns en 'team' user också som ska kunna användas istället för root men lyckades inte pusha med den.

**Comment by meristakovska** [comment]
@rassek96 Jag vet inte hur känslig informationen är men repot är publikt?

**Comment by rassek96** [comment]
@meristakovska Hm, det tänkte jag inte ens på. Jag tar och bytar lösenord för säkerhets skull.
