### ISSUE TITLE
Youtube API auth (Prio 1)

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#45]

**Comment by rassek96** [comment]
Hej, här kommer lite information om Youtubes API som jag hittat än så länge, om det kan vara till någon hjälp.

https://www.googleapis.com/youtube/v3/channels?part=statistics&forUsername={username}&key={YOUTUBE_API_KEY}
Borde ge ut totala summan av visningar på en kanal.
Behöver API-key, authentisering.

Modulen 'youtube-api' kan kanske användas.
https://www.npmjs.com/package/youtube-api
