### ISSUE TITLE
Projektvision

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#5]
Mall: Tobbe

**Comment by meristakovska** [comment]
https://github.com/1DV611/effect-reklambyra/wiki/Projektvision

**Comment by meristakovska** [comment]
Innan veckans (v. 13) slut bör vi skicka ett utkast (baserat på kundens projektbeskrivning och mötesinnehållet) som vi kan få feedback på från kunden. Jag skickar därefter visionen till kunden för signering.

**Comment by meristakovska** [comment]
Projektvision skickad till Erik för underskrift (https://drive.google.com/open?id=0Bx-IzqAzLZAeeEtVRnlIS25Wa1k)

**Comment by meristakovska** [comment]
Projektvision signerad: https://github.com/1DV611/effect-reklambyra/wiki/Projektvision
