### ISSUE TITLE
Linkedin API (Prio 1)

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#50]

**Comment by rassek96** [comment]
Hej, här kommer lite information om LinkedIns API som jag hittat än så länge, om det kan vara till någon hjälp.

https://api.linkedin.com/v1/companies/{company_id}/company-statistics
Borde ge ut statistiken för ett företag.
Behöver access token, authentisering.

Modulen 'node-linkedin' kan kanske användas.
https://www.npmjs.com/package/node-linkedin
