### ISSUE TITLE
Generera PDF

### ISSUE THREAD

**Issue by sehnpaa** [1DV611/effect-reklambyra#77]
Jag har börjat i och med https://github.com/1DV611/effect-reklambyra/commit/ec03c2d59d35af4f99a8e0893ab2a19d512b7b71.

Formatteringen kan förbättras genom att konkatenera html-strängen med views/partials/head.handlebars.

Diagrammen visar fel eftersom pdf-en genereras innan diagram-animationen är färdig. Det kan lösas med åtminstone 1) att phantomjs-html-to-pdf istället används för konverteringen och att man sätter en godtycklig delay innan konvertering görs eller 2) att diagrammets animation tas bort. Jag har testat att "1)" fungerar, medan jag endast antar att "2)" fungerar. 

@tobbe: Kan du tänka dig vi kör utan animation? Isåfall provar jag hellre på "2)" för att slippa godtycklig delay.

**Comment by Tobbe** [comment]
Funkar för mig att köra utan animation, men taggade du verkligen rätt person? ;)

**Comment by sehnpaa** [comment]
Ahh, det där blev ju helt fel, ja. Ursäkta bruset! Även om det känns tryggt med ditt medgivande så krävs nog ett godkännade från @Toubic också. :-)

**Comment by sehnpaa** [comment]
Löst tidigare med e8037739f2fe9225b28026cc09b9e70bf4be0b4b och några efterföljande commits.
