### ISSUE TITLE
Auth popup

### ISSUE THREAD

**Issue by larswww** [1DV611/effect-reklambyra#84]
auth för varje kanal ligger på /auth/kanal, t ex http://siteurl.com/auth/instagram 

Koppla det till view

**Comment by sehnpaa** [comment]
I och med cc92e34c6f66a9c975cae945ae057830bc10f93d så öppnas en ny flik med respektive tredjeparts-authentisering när man aktiverar en switch i Settingsvyn. Är det något mer du tänkte på? Det hade varit nice om switchens status beror på huruvida vi har en giltig token eller ej, med det kanske är utanför denna issuens scope?

**Comment by larswww** [comment]
Utanför denna issues scope men helt rätt tänkt
